### ISSUE TITLE
a problem 

### ISSUE THREAD

**Issue by gongliuqing123** [MaciDE/YOLOv8-seg-iOS#2]
the problem is could not determine generated file paths for coreml code generation:...

**Comment by MaciDE** [comment]
You have to add your own coreml models to the project and change the class in line 131 and line 374 so that it fits your model.

**Comment by gongliuqing123** [comment]
thank you very much, the model is yolov8-seg official can use it?

**Comment by gongliuqing123** [comment]
i have meet another problem is that unable to open cinfiguration setting file,can you help me

**Comment by MaciDE** [comment]
> thank you very much, the model is yolov8-seg official can use it?

Yes, the code works with yolov8-seg models trained and exported with the scripts provided by the official ultralytics repo.

**Comment by MaciDE** [comment]
> i have meet another problem is that unable to open cinfiguration setting file,can you help me

Please provide more information e.g. a screenshot of your issue. Alternatively I just added some already exported yolov8n-seg models to this repo.

**Comment by gongliuqing123** [comment]
thank you very mach , i have solve it , but when i deploy to the iphone, outputs socre is 0 ,to the simulation iphone, the output score is good , so i want to konw , are you meet the problem?

**Comment by MaciDE** [comment]
No it works on the simulator and on a real device.
