### ISSUE TITLE
metal

### ISSUE THREAD

**Issue by gongliuqing123** [MaciDE/YOLOv8-seg-iOS#3]
thank you very much , do you  know that pytorch model inference with metal accelerate, because current model is slowly

**Comment by MaciDE** [comment]
@gongliuqing123 as far as I know pytorch mobile does not support running models using metal. If you want to use metal for hardware acceleration you can run the model using the vision framework or TensorFlow Lite's metal delegate.

**Comment by gongliuqing123** [comment]
ok, thank you  very much
