### ISSUE TITLE
coreml in iphone error

### ISSUE THREAD

**Issue by gongliuqing123** [MaciDE/YOLOv8-seg-iOS#4]
Hi，thank you for your code, but when i use the coreml inference code  deploy in my iphone, all outputs are zeros, can you help me ?

**Comment by MaciDE** [comment]
Inference using only Core ML is something I still have to figure out because the model's outputs are quite strange. But you can use the vision framework together with the Core ML model.

**Comment by gongliuqing123** [comment]
yes, i have try version framework inference ,but the outputs not correct。for example, first test is right, second test is wrong,do you know the reason and help me? thank you very much
