### ISSUE TITLE
Problem about ultralytics official exported model 

### ISSUE THREAD

**Issue by Greywan** [MaciDE/YOLOv8-seg-iOS#5]
Thank you very much for your work!
I converted YOLOv8n-seg to tflite according to the official library of ultralytics, put it back into xcode and compiled it, but the result is very strange, it doesn't output the normal result.
The tflite in your project.
![image](https://github.com/MaciDE/YOLOv8-seg-iOS/assets/61035902/2a5b7929-4029-408a-970c-76e3d94d2375)
The tflite I re-exported
![image](https://github.com/MaciDE/YOLOv8-seg-iOS/assets/61035902/92954a85-c01c-4da9-a052-03c53ee4a4e4)
![image](https://github.com/MaciDE/YOLOv8-seg-iOS/assets/61035902/e0f85c93-5ab8-4dc0-852c-6107e98a3349)

The original result of your original project,
![image](https://github.com/MaciDE/YOLOv8-seg-iOS/assets/61035902/33a2f7e4-e87b-4a00-8590-6c3b73ec1f8b)
The result after model export
![image](https://github.com/MaciDE/YOLOv8-seg-iOS/assets/61035902/1a4deb00-ce54-4a22-9125-f70fa38f6db2)

I followed the following procedure for model exporting
`from ultralytics import YOLO`
`model = YOLO('yolov8n-seg.pt')`
`model.export(format='tflite')`

**Comment by MaciDE** [comment]
Hey, I can confirm that there is indeed a problem with YOLOv8 models that are exported to .tflite. I will look if I have some time next week to figure out what's wrong.

**Comment by MaciDE** [comment]
@Greywan I pushed some changes to the repo that should fix the issue.

**Comment by Greywan** [comment]
> @Greywan I pushed some changes to the repo that should fix the issue.

Thank you for your efforts,I will give it a try.

**Comment by MaciDE** [comment]
Any update, @Greywan?

**Comment by Greywan** [comment]
> Any update, @Greywan?
No more. Your changes worked.Thanks

**Comment by Greywan** [comment]
> Any update, @Greywan?

No more. Your changes worked.Thanks
