### ISSUE TITLE
Is yolov8 effective for detecting handwritten letters?

### ISSUE THREAD

**Issue by BayramBayramli1** [MaciDE/YOLOv8-seg-iOS#6]
I want to fine-tune Yolov8 for detecting handwritten letters. Lets say 50 characters need to be detected. How many images per letter should be provided? How many different backgrounds needed? Size of images must be same? 224,512 or 1024 as imgz is better? Is it possible to train letters separately then combine model weights?

**Comment by MaciDE** [comment]
I think it's better to ask these questions in the official yolov8 repo. https://github.com/ultralytics/ultralytics
