### ISSUE TITLE
The coreml model option does not work properly

### ISSUE THREAD

**Issue by lizhiwen19900709** [MaciDE/YOLOv8-seg-iOS#8]
The coreml model option does not work properly，Click run inference No invalid！

**Comment by MaciDE** [comment]
The Core ML model is working fine. It's just the option to inference the model solely using Core ML that is still work in progress because of problems with the output. If you want to use the Core ML model you can use the Vision framework.

**Comment by lizhiwen19900709** [comment]
> The Core ML model is working fine. It's just the option to inference the model solely using Core ML that is still work in progress because of problems with the output. If you want to use the Core ML model you can use the Vision framework.

Consider calling up a real-time segmentation version of the video header?

**Comment by MaciDE** [comment]
No, while some YOLOv8 variants in combination with frameworks like Vision may be suitable to perform real-time segmentation the post-processing in this repo would be way to slow. If you want to perform real-time segmentation you would rely on performing the post-processing part on the GPU using Metal.

**Comment by lizhiwen19900709** [comment]
> No, while some YOLOv8 variants in combination with frameworks like Vision may be suitable to perform real-time segmentation the post-processing in this repo would be way to slow. If you want to perform real-time segmentation you would rely on performing the post-processing part on the GPU using Metal.

Can I get a real-time split?

**Comment by MaciDE** [comment]
Split of what?

**Comment by lizhiwen19900709** [comment]
> Split of what?

Split image content in real time using mobile phone cameras

**Comment by MaciDE** [comment]
No, this project is just an example on how to perform instance segmentation using YOLOv8 with various mobile inference frameworks on iOS.
